### ISSUE TITLE
Pull more than 60 results with multiple small radius searches

### ISSUE THREAD

**Issue by joshtronic** [joshtronic/php-googleplaces#5]
originally posted by @bristweb on issue #4 :

One other thing on a similar vein, but not really specific to this project. Google definitely limits a particular search to 60 results. I had hoped that I could just spend more of my quota in order to get an exhaustive dataset, but apparently that isn't possible without a bunch of legwork. The only way I can think of to accomplish this is to do a whole ton of small radius searches - resulting in something like this: http://cdn2.techworld.com/cmsdata/slideshow/3310742/09_crop_circles_thumb555.jpg

**Comment by joshtronic** [comment]
Been sitting around over a year, gonna close it out. Re-open if ya need to!

**Comment by PadamSethia** [comment]
Hey ! Thanks for the breakdown , But I'd like to know if this method still works ?
